### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by josuebrunel** [CongoLUG/website#2]
@CongoLUG/owners un Tux sur le drapeau du Congo. Enfin si vous savez le faire :wink: , je suis nul en photoshop

**Comment by rajilsaj** [comment]
Ok daccord je my met lol :)

**Comment by rajilsaj** [comment]
Oups ! De oups !

**Comment by kounkou** [comment]
Ahah, un mois déjà... Tick tick

**Comment by rajilsaj** [comment]
Congo Tux bro's

On Thu, Sep 17, 2015 at 9:51 PM, Jacques notifications@github.com wrote:

> Ahah, un mois déjà... Tick tick
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CongoLUG/website/issues/2#issuecomment-141224480.

## 

Product Manager and Web Developer

**Comment by rajilsaj** [comment]
Hi CongoLUG/website,

I'd like to add you to my professional network on LinkedIn.

- Rajil

Confirm that you know Rajil: https://www.linkedin.com/e/v2?e=0-ion4hkxt-ce&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=zlp4B4z6&invitationId=6141282994708631552








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ion4hkxt-ce&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQH3HDqFHNo1DgAAAVTo4dgZEmUivVo2rI4S6W5NZHMOvTSmpK-U45NzXLxBTJljTDdRsIJhPsp_QgD4ROEO6vY0WRA8IRS3wFKnsrgQQlreqIZOI9XpyMJ3HZcTlp1EhF0BB5toFGl8hGVJDojbVHvktbzQt_w0TIfsVuzPg7e8zqn_jnYV66OqqO9lwGtzxGPS&eid=0-ion4hkxt-ce


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ion4hkxt-ce&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Hi CongoLUG/website,

I'd like to add you to my professional network on LinkedIn.

- Rajil

Confirm that you know Rajil: https://www.linkedin.com/e/v2?e=0-ion4hq5d-fq&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=xUNQXO43&invitationId=6141282995467804673








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ion4hq5d-fq&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQE19obildKnDAAAAVTo4ezz6qZYA7w6vaqdAW0JlEl9F1p5in19MpP9C13P4Nxi8tLapJ5GZKBe0_w_i8MTmMJ-cAKp8--Ifq8ZZJMU_4nM5JqkvApyE3mLbCUjvNWOdVKfZR_tSTUKjphbgPC1dywq-1BX4hlgI53aD0fzLUjHsFE8vRLxPc8roM3PET-xczhW&eid=0-ion4hq5d-fq


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ion4hq5d-fq&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=zlp4B4z6&invitationId=6141282994708631552&trk=eml-first_guest_reminder_01-hero-14-accept_text&trkEmail=eml-first_guest_reminder_01-hero-14-accept_text-null-%7Eq525cf%7Eiowuv8vs%7E6g

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=zlp4B4z6&invitationId=6141282994708631552&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Eq525cf%7Eiowuv8vs%7E6g





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-q525cf-iowuv8vs-6g&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-q525cf-iowuv8vs-6g&loid=AQH7shvjsYUSnQAAAVUM-lQ5CMB4Z0jtAwbxtk_p7eqPSNkDCjhEjc6qPWKGAjfF--Tu3tuq042n-j1zC4B2bmfA3KWEdTXri7SxB88K1VbxbhFgdzafdhNyr8V0lDIBWPYEW67cTenlzq8GdZAas7NJJ8JHu_0qz7s3UULm94PX20XMHDN2lE8J4AgMzLpOLsds

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-q525cf-iowuv8vs-6g&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by rajilsaj** [comment]
Rajil VEMBE would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-q525cf-ip6v2q7q-ue&t=ssuw&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=zlp4B4z6&invitationId=6141282994708631552

View Rajil VEMBE&#39;s profile: https://www.linkedin.com/e/v2?e=-q525cf-ip6v2q7q-ue&t=ssuw&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=zlp4B4z6&invitationId=6141282994708631552





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-q525cf-ip6v2q7q-ue&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-q525cf-ip6v2q7q-ue&loid=AQFNwOCk_BniEwAAAVUw-M6VjY5iOtRvd1xRU3QijGzlowfKOl8_1uka3w6aex7Ppajvm-13zgEicpagmKgwP2BZPnHBmdPUCC1i6YMvM6Cd3NGL31xELN0TGWjP4QI5sqFVc_8qwpcB_YiNvEU_VSq5jWsc7bi85hkTEgYXkkEfypqWaVKk1ZxLY_2MJPwVuuqW

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-q525cf-ip6v2q7q-ue&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
